zones:
- id: zp_mtvc30da
  name: Zone_1
  type: palette
  kind: palette
  severity: info
  polygon:
  - - -1.823
    - 0.275
  - - -1.829
    - 1.416
  - - -0.613
    - 1.391
  - - -0.635
    - 0.24
  derived_from: zone_patch
  z_base_m: 0.304
